[package]
name = "extract-content-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
pdf-extract = "0.8.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
